Feature/fs 14
k0dm/FakeStore pull request #14
Opened 2024-03-20 16:49 UTC by Deizerok

https://kanbanflow.com/t/LAM3DmRA

2024-03-20 18:20 UTC, k0dm requested changes

2024-03-20 18:20 UTC, bugbenderx commented on app/src/main/java/com/example/fakestore/content/products/presentation/ProductPositionLiveDataWrapper.kt
> +        init {
remove init

2024-03-20 18:20 UTC, bugbenderx commented on app/src/main/java/com/example/fakestore/content/products/presentation/ProductsViewModel.kt
>      override fun goToProductsDetails(id: Int, category: String) {
no need category

2024-03-20 18:20 UTC, bugbenderx commented on app/src/test/java/com/example/fakestore/content/products/presentation/ProductDetailsViewModelTest.kt
> +        viewModel.goToProducts(1)
add explicit name argument

2024-03-20 18:20 UTC, bugbenderx commented on app/src/test/java/com/example/fakestore/content/products/presentation/ProductDetailsViewModelTest.kt
> +        viewModel.goToProducts(1)
check value in productPositionLiveDataWrapper

2024-03-20 18:20 UTC, k0dm commented on app/src/test/java/com/example/fakestore/content/products/presentation/ProductDetailsViewModelTest.kt
> +    override suspend fun changeAddedToCart(id: Int): Int {
override suspend fun changeAddedToCart(id: Int): Int {
        return if (changeAddedToCartCalledCount++ %2 == 0) {
            cache = cache.copy(addedToCart = true)
            1
        }else {
            cache = cache.copy(addedToCart = false)
            0
        }
    }

2024-03-20 18:20 UTC, k0dm commented on app/src/test/java/com/example/fakestore/content/products/presentation/ProductDetailsViewModelTest.kt
> +    override suspend fun changeFavorite(id: Int) {
see override suspend fun changeAddedToCart but without return Int

2024-03-20 18:51 UTC, Deizerok commented on app/src/main/java/com/example/fakestore/content/products/presentation/ProductsViewModel.kt
>      override fun goToProductsDetails(id: Int, category: String) {
geniy how do i make a retry without a category

2024-03-22 08:02 UTC, k0dm approved these changes

2024-03-22 08:02 UTC, merged